# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af60fca82bf6a5579a044bb4f5bd6d8a9bfd9a12650c7742ff7b5d375e3ef81d8b5781a2aa337292cb9e3c8113bcbf6f3f21948e5f9c0a5f4cbf992d51c6ff66

test:
  secret_key_base: be1a0ab0d18842fdb5fa618a202a74810366f584eb1cb5fde26cf70ff6d24a345b101b03ca51ee28dc821f2e7feb238253cdbd38cc0ea9562b511c16ce2d60e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
